### PR TITLE
Typos grammar fixes

### PR DESCRIPTION
**Pull request by chrisdopuch**
Hello,

Here are some quick grammatical fixes and typo corrections that I made while using your app for the first time. Very good job, really enjoyed using it!

I am interested in continuing to contribute to this application, if help is desired.  

(P.S. Mein Deutsch ist nicht so gut, aber ich kann es gut genug verstehen. Es ist kein Problem für mich diese Issues auf Deutsch zu lesen)

### CODE REVIEW

**Comment by chrisdopuch** [comment]
I forgot to mention, I was unable to get the grunt tests running in a Windows environment, using Node 4. You should probably run the tests locally on this branch before merging, although it may be irrelevant since all the changes were just textual.

**Comment by pumpi** [comment]
Hi,

Thanks for your work. The Grunt only merges the JS files and make the CSS from the Sass. i only run the dev-watch or the production task. At the moment i have lokal an change for move models between groups. I look how i can add your changes im not so good with working on github.

P.S. My english gramataic is not so good but i hope you can understand ;)

**Comment by pumpi** [comment]
sorry i must make some changes by myself an hand my structure have make an big change since last update but your changes are online i think ;)

**Comment by chrisdopuch** [comment]
Thanks for merging! :+1: 
I looked online at the app -- all the changes look good except one thing. The "objecitve" typo is still there. IIRC there was a built version and a source version, and I only edited the source (since I assumed that building the app was part of deploy process). 
You may need to rebuild the app and redeploy to get the new fix. 
Or maybe I just added it to the wrong place?

**Comment by pumpi** [comment]
oh that my fault i change this and push it sorry one thing i forgot to merge manually
This was in the build template there is no need to rebuild only the JS file need an grunt dev-watch or productive task

**Pull request merged**
